include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    prefer_final_locals: true
    prefer_relative_imports: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: false
    avoid_print: false  # Allow print for debugging
