targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - lib/src/models/**.dart
      
      freezed:
        options:
          # Options for freezed
          copy_with: true
          equal: true
          to_string: true
        generate_for:
          - lib/src/models/**.dart
