name: flutter_wordpress2
description: A comprehensive Flutter plugin for WordPress platform integration with enhanced architecture, backward compatibility, authentication, content management, offline support, and advanced features
version: 0.2.1
homepage: https://github.com/libsFlutter/flutter_wordpress2
repository: https://github.com/libsFlutter/flutter_wordpress2
issue_tracker: https://github.com/libsFlutter/flutter_wordpress2/-/issues
documentation: https://github.com/libsFlutter/flutter_wordpress2/-/wikis
topics:
  - wordpress
  - cms
  - flutter
  - api
  - compatibility

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Platform Interface
  plugin_platform_interface: ^2.1.8
  
  # HTTP Client
  dio: ^5.9.0
  http: ^1.5.0
  
  # State Management
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  provider: ^6.1.5
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Immutable Models
  freezed_annotation: ^3.1.0
  
  # API Client Generation
  retrofit: ^4.7.2
  
  # Local Storage (Latest 2025)
  shared_preferences: ^2.5.3
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  
  # Image Caching
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  visibility_detector: ^0.4.0+2
  
  # Network Connectivity
  connectivity_plus: ^7.0.0
  
  # Device Information
  device_info_plus: ^12.1.0
  
  # Security
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  
  # Logging
  logger: ^2.6.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Offline Support
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  
  # Real-time Communication
  socket_io_client: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation (Latest 2025)
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  drift_dev: ^2.28.2
  freezed: ^3.2.3
  retrofit_generator: ^10.0.5
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing (Latest 2025)
  mockito: ^5.4.4
  mocktail: ^1.0.4
  test: ^1.26.2
  alchemist: ^0.12.1
  patrol: ^3.19.0
  
  # Test Coverage
  coverage: ^1.15.0


flutter:
  # This section identifies this package as a Flutter plugin
  plugin:
    platforms:
      android:
        package: ru.nativemind.flutter.magento.flutter_magento
        pluginClass: FlutterMagentoPlugin
      ios:
        pluginClass: FlutterMagentoPlugin
      linux:
        pluginClass: FlutterMagentoPlugin
      macos:
        pluginClass: FlutterMagentoPlugin
      windows:
        pluginClass: FlutterMagentoPlugin
      web:
        pluginClass: FlutterMagentoPlugin
        fileName: flutter_magento_web.dart

  # To add assets to your plugin package, add an "assets" section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a "fonts" section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages


